package frontend;

import backend.BazaDanych;
import java.awt.Color;
import java.text.Normalizer;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

public class SlowaFrame extends javax.swing.JFrame {
    
    private int kategoriaId;
    private Map<String, String> slowkaMapa;
    private List<String> polskieSlowa;
    private int biezacyIndeks = 0;
    private String jezyk = "pl";
    private long czasStartowy;
    private int poprawneOdpowiedzi = 0;
    
    
    public SlowaFrame(int kategoriaId) {
        this.kategoriaId = kategoriaId;
        this.kategoriaId = kategoriaId;
        this.czasStartowy = System.currentTimeMillis(); // Start licznika czasu
        
        setTitle("Fiszki - słówka");
        setSize(550, 400);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        initComponents();
        setLocationRelativeTo(null);
        ustawFlagi();

        // Pobieranie słówek z bazy danych
        slowkaMapa = BazaDanych.pobierzSlowka(kategoriaId);
        polskieSlowa = new ArrayList<>(slowkaMapa.keySet());
        
        if (slowkaMapa.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Brak słówek dla wybranej kategorii!", "Informacja", JOptionPane.WARNING_MESSAGE);
            dispose();
            return;
        }
        aktualizujSlowo(); // Wyświetl pierwsze słówko
        setVisible(true);
    }
    
    private void ustawFlagi() {
        ImageIcon flagaEs = new ImageIcon(getClass().getResource("/img/es.png"));
        ImageIcon flagaPl = new ImageIcon(getClass().getResource("/img/pl.png"));
        btnPl.setIcon(flagaPl);
        btnEs.setIcon(flagaEs);
    }
    
    
    //odwrócenie mapy z pol -> hiszp na hiszp -> pol
    private Map<String, String> odwroconaSlowkaMapa(Map<String, String> slowkaMapa) {
        Map<String, String> odwroconaMapa = new HashMap<>();
        for (Map.Entry<String, String> entry : slowkaMapa.entrySet()) {
            odwroconaMapa.put(entry.getValue(), entry.getKey()); // Zamiana miejscami
        }
        return odwroconaMapa;
    }
    
    
    //wyświetlanie polskich słów
    private void aktualizujSlowo() {
        String slowo = polskieSlowa.get(biezacyIndeks);
        
        if (jezyk.equals("pl")) {
            lblSlowko.setText(slowo);
        } else if (jezyk.equals("es")) {
            lblSlowko.setText(slowkaMapa.get(slowo));
        }
        lblLicznik.setText("Słówko " + (biezacyIndeks + 1) + "/" + polskieSlowa.size());
        txtOdpowiedz.setText("");
    }
    
    
    private String normalizujTekst(String tekst) {
        if (tekst == null) return "";
        tekst = Normalizer.normalize(tekst, Normalizer.Form.NFC); // Normalizacja do jednolitego formatu
        return tekst.replace("\u00A0", " ") // Zamiana twardej spacji (NBSP) na zwykłą
                    .replaceAll("\\s+", " ") // Zamiana wielu spacji na jedną
                    .trim(); // Usunięcie spacji na początku i końcu
}
    
    private void sprawdzOdpowiedz() {
        String odpowiedz = normalizujTekst(txtOdpowiedz.getText());
        String polskieSlowo = polskieSlowa.get(biezacyIndeks);
        String poprawneTlumaczenie = normalizujTekst(slowkaMapa.get(polskieSlowo));
       
        if (jezyk.equals("pl")) {
            poprawneTlumaczenie = normalizujTekst(slowkaMapa.get(polskieSlowo));    
        } else {
            Map<String, String> reversed = odwroconaSlowkaMapa(slowkaMapa);
            poprawneTlumaczenie = normalizujTekst(reversed.get(slowkaMapa.get(polskieSlowo)));
        }
        
        if (odpowiedz.equalsIgnoreCase(poprawneTlumaczenie)) { // Sprawdzenie poprawności (bez uwzględniania wielkości liter)
            lblWynik.setText("Poprawnie!");
            lblWynik.setForeground(Color.GREEN); // Zielony kolor dla poprawnej odpowiedzi
            poprawneOdpowiedzi++;
        } else {
            lblWynik.setText("Niepoprawnie! Spróbuj ponownie.");
            lblWynik.setForeground(Color.RED); // Czerwony kolor dla błędnej odpowiedzi
        }
    }


    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> new SlowaFrame(1)); // Przykład: kategoriaId = 1
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlStrzalki = new javax.swing.JPanel();
        btnWstecz = new javax.swing.JButton();
        lblLicznik = new javax.swing.JLabel();
        btnDalej = new javax.swing.JButton();
        pnlTlumaczenie = new javax.swing.JPanel();
        lblWpiszTlumaczenie = new javax.swing.JLabel();
        lblSlowko = new javax.swing.JLabel();
        txtOdpowiedz = new javax.swing.JTextField();
        btnSprawdz = new javax.swing.JButton();
        btnA = new javax.swing.JButton();
        btnE = new javax.swing.JButton();
        btnI = new javax.swing.JButton();
        btnN = new javax.swing.JButton();
        btnU = new javax.swing.JButton();
        btnUUmlaut = new javax.swing.JButton();
        lblWynik = new javax.swing.JLabel();
        btnPrawidlowa = new javax.swing.JButton();
        btnPl = new javax.swing.JButton();
        btnEs = new javax.swing.JButton();
        mbrSlowa = new javax.swing.JMenuBar();
        mnuStronaGlowna = new javax.swing.JMenu();
        mniStronaGlowna = new javax.swing.JMenuItem();
        mnuPomoc = new javax.swing.JMenu();
        mniJakKorzystac = new javax.swing.JMenuItem();
        mnuWyjscie = new javax.swing.JMenu();
        mniWyjdz = new javax.swing.JMenuItem();

        btnWstecz.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnWstecz.setText("<");
        btnWstecz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWsteczActionPerformed(evt);
            }
        });

        lblLicznik.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLicznik.setText("Licznik");

        btnDalej.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDalej.setText(">");
        btnDalej.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDalejActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlStrzalkiLayout = new javax.swing.GroupLayout(pnlStrzalki);
        pnlStrzalki.setLayout(pnlStrzalkiLayout);
        pnlStrzalkiLayout.setHorizontalGroup(
            pnlStrzalkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStrzalkiLayout.createSequentialGroup()
                .addComponent(btnWstecz, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLicznik, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(184, 184, 184)
                .addComponent(btnDalej, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlStrzalkiLayout.setVerticalGroup(
            pnlStrzalkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStrzalkiLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnlStrzalkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLicznik)
                    .addComponent(btnDalej)
                    .addComponent(btnWstecz))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        lblWpiszTlumaczenie.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblWpiszTlumaczenie.setText("Wpisz poprawne tłumaczenie słowa:");

        lblSlowko.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSlowko.setText("słowo");

        txtOdpowiedz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOdpowiedzActionPerformed(evt);
            }
        });

        btnSprawdz.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSprawdz.setText("Sprawdź poprawność");
        btnSprawdz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSprawdzActionPerformed(evt);
            }
        });

        btnA.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnA.setText("á");
        btnA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAActionPerformed(evt);
            }
        });

        btnE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnE.setText("é");
        btnE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEActionPerformed(evt);
            }
        });

        btnI.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnI.setText("í");
        btnI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIActionPerformed(evt);
            }
        });

        btnN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnN.setText("ñ");
        btnN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNActionPerformed(evt);
            }
        });

        btnU.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnU.setText("ú");
        btnU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUActionPerformed(evt);
            }
        });

        btnUUmlaut.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUUmlaut.setText("ü");
        btnUUmlaut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUUmlautActionPerformed(evt);
            }
        });

        btnPrawidlowa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPrawidlowa.setText("Pokaż prawidłową odpowiedź");
        btnPrawidlowa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrawidlowaActionPerformed(evt);
            }
        });

        btnPl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlActionPerformed(evt);
            }
        });

        btnEs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTlumaczenieLayout = new javax.swing.GroupLayout(pnlTlumaczenie);
        pnlTlumaczenie.setLayout(pnlTlumaczenieLayout);
        pnlTlumaczenieLayout.setHorizontalGroup(
            pnlTlumaczenieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTlumaczenieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTlumaczenieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTlumaczenieLayout.createSequentialGroup()
                        .addGroup(pnlTlumaczenieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnPrawidlowa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                            .addComponent(txtOdpowiedz, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSprawdz, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(pnlTlumaczenieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlTlumaczenieLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblWynik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlTlumaczenieLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnI)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnU)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnUUmlaut)
                                .addContainerGap(64, Short.MAX_VALUE))))
                    .addGroup(pnlTlumaczenieLayout.createSequentialGroup()
                        .addGroup(pnlTlumaczenieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSlowko, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlTlumaczenieLayout.createSequentialGroup()
                                .addComponent(lblWpiszTlumaczenie, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEs)))
                        .addContainerGap())))
        );
        pnlTlumaczenieLayout.setVerticalGroup(
            pnlTlumaczenieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTlumaczenieLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlTlumaczenieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPl)
                    .addComponent(lblWpiszTlumaczenie)
                    .addComponent(btnEs))
                .addGap(13, 13, 13)
                .addComponent(lblSlowko)
                .addGap(10, 10, 10)
                .addGroup(pnlTlumaczenieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOdpowiedz, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnN)
                    .addComponent(btnU)
                    .addComponent(btnUUmlaut)
                    .addComponent(btnA)
                    .addComponent(btnE)
                    .addComponent(btnI))
                .addGap(18, 18, 18)
                .addGroup(pnlTlumaczenieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSprawdz)
                    .addComponent(lblWynik))
                .addGap(18, 18, 18)
                .addComponent(btnPrawidlowa)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        mnuStronaGlowna.setText("Strona główna");

        mniStronaGlowna.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniStronaGlowna.setText("Przejdź do strony głównej");
        mniStronaGlowna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniStronaGlownaActionPerformed(evt);
            }
        });
        mnuStronaGlowna.add(mniStronaGlowna);

        mbrSlowa.add(mnuStronaGlowna);

        mnuPomoc.setText("Pomoc");

        mniJakKorzystac.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniJakKorzystac.setText("Jak korzystać z fiszek?");
        mniJakKorzystac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniJakKorzystacActionPerformed(evt);
            }
        });
        mnuPomoc.add(mniJakKorzystac);

        mbrSlowa.add(mnuPomoc);

        mnuWyjscie.setText("Wyjście");

        mniWyjdz.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniWyjdz.setText("Wyjdź");
        mniWyjdz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniWyjdzActionPerformed(evt);
            }
        });
        mnuWyjscie.add(mniWyjdz);

        mbrSlowa.add(mnuWyjscie);

        setJMenuBar(mbrSlowa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlTlumaczenie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlStrzalki, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTlumaczenie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(pnlStrzalki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnWsteczActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWsteczActionPerformed
        if (biezacyIndeks > 0) {
                biezacyIndeks--;
                aktualizujSlowo();
            } else {
                JOptionPane.showMessageDialog(this, "To jest pierwsze słówko!", "Informacja", JOptionPane.INFORMATION_MESSAGE);
            }
    }//GEN-LAST:event_btnWsteczActionPerformed

    private void txtOdpowiedzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOdpowiedzActionPerformed
        txtOdpowiedz.setText("");
        txtOdpowiedz.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    }//GEN-LAST:event_txtOdpowiedzActionPerformed

    private void btnAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAActionPerformed
        txtOdpowiedz.setText(txtOdpowiedz.getText() + "á");
    }//GEN-LAST:event_btnAActionPerformed

    private void btnUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUActionPerformed
        txtOdpowiedz.setText(txtOdpowiedz.getText() + "ú");
    }//GEN-LAST:event_btnUActionPerformed

    private void mniWyjdzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniWyjdzActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mniWyjdzActionPerformed

    private void btnDalejActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDalejActionPerformed
        if (biezacyIndeks < slowkaMapa.size() - 1) {
            biezacyIndeks++;
            aktualizujSlowo();
        } else {
            long czasKoncowy = System.currentTimeMillis();
            double czasNaukiSekundy = (czasKoncowy - czasStartowy) / 1000.0;

            double procentPoprawnych = (double) poprawneOdpowiedzi / slowkaMapa.size() * 100;
            procentPoprawnych = Math.round(procentPoprawnych * 100.0) / 100.0;

            // Tworzymy nowe okno z wynikami
            StatystykiFrame koniec = new StatystykiFrame(poprawneOdpowiedzi, slowkaMapa.size(), procentPoprawnych, czasNaukiSekundy);
            koniec.setVisible(true);
        }
    }//GEN-LAST:event_btnDalejActionPerformed

    private void btnSprawdzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSprawdzActionPerformed
        sprawdzOdpowiedz();
    }//GEN-LAST:event_btnSprawdzActionPerformed

    private void btnEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEActionPerformed
        txtOdpowiedz.setText(txtOdpowiedz.getText() + "é");
    }//GEN-LAST:event_btnEActionPerformed

    private void btnIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIActionPerformed
        txtOdpowiedz.setText(txtOdpowiedz.getText() + "í");
    }//GEN-LAST:event_btnIActionPerformed

    private void btnNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNActionPerformed
        txtOdpowiedz.setText(txtOdpowiedz.getText() + "ñ");
    }//GEN-LAST:event_btnNActionPerformed

    private void btnUUmlautActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUUmlautActionPerformed
        txtOdpowiedz.setText(txtOdpowiedz.getText() + "ü");
    }//GEN-LAST:event_btnUUmlautActionPerformed

    private void btnPrawidlowaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrawidlowaActionPerformed
        String polskieSlowo = polskieSlowa.get(biezacyIndeks);
        String poprawneTlumaczenie = slowkaMapa.get(polskieSlowo);
        txtOdpowiedz.setText(poprawneTlumaczenie); // Wstaw poprawne tłumaczenie do pola tekstowego
    }//GEN-LAST:event_btnPrawidlowaActionPerformed

    private void btnEsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsActionPerformed
        jezyk = "es";  // Ustaw język na hiszpański
        aktualizujSlowo();  // Zaktualizuj słówko
    }//GEN-LAST:event_btnEsActionPerformed

    private void btnPlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlActionPerformed
        jezyk = "pl";  // Ustaw język na polski
        aktualizujSlowo();  // Zaktualizuj słówko 
    }//GEN-LAST:event_btnPlActionPerformed

    private void mniStronaGlownaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniStronaGlownaActionPerformed
        new StartFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mniStronaGlownaActionPerformed

    private void mniJakKorzystacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniJakKorzystacActionPerformed
        JOptionPane.showMessageDialog(SlowaFrame.this, 
            "W prawym górnym rogu wybierz język, z którego chciałbyś tłumaczyć słówka.\nW polu tekstowym wpisz tłumaczenie. Wielkość liter i ilość spacji nie ma znaczenia.\nKorzystaj z przycisków ze znakami diaktrycznymi - są brane pod uwagę!\nAby sprawdzić poprawność tłumaczenia wciśnij odpowiedni przycisk.\nTak samo w przypadku, gdy chcesz od razu wyświetlić gotowe tłumaczenie.\nW celu przechodzenia między słówkami poruszaj się za pomocą strzałek.\nPowodzenia i miłej zabawy!",
            "Jak korzystać z fiszek?",
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_mniJakKorzystacActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnA;
    private javax.swing.JButton btnDalej;
    private javax.swing.JButton btnE;
    private javax.swing.JButton btnEs;
    private javax.swing.JButton btnI;
    private javax.swing.JButton btnN;
    private javax.swing.JButton btnPl;
    private javax.swing.JButton btnPrawidlowa;
    private javax.swing.JButton btnSprawdz;
    private javax.swing.JButton btnU;
    private javax.swing.JButton btnUUmlaut;
    private javax.swing.JButton btnWstecz;
    private javax.swing.JLabel lblLicznik;
    private javax.swing.JLabel lblSlowko;
    private javax.swing.JLabel lblWpiszTlumaczenie;
    private javax.swing.JLabel lblWynik;
    private javax.swing.JMenuBar mbrSlowa;
    private javax.swing.JMenuItem mniJakKorzystac;
    private javax.swing.JMenuItem mniStronaGlowna;
    private javax.swing.JMenuItem mniWyjdz;
    private javax.swing.JMenu mnuPomoc;
    private javax.swing.JMenu mnuStronaGlowna;
    private javax.swing.JMenu mnuWyjscie;
    private javax.swing.JPanel pnlStrzalki;
    private javax.swing.JPanel pnlTlumaczenie;
    private javax.swing.JTextField txtOdpowiedz;
    // End of variables declaration//GEN-END:variables

}
