
package frontend;

import frontend.SlowaFrame;
import backend.BazaDanych;
import java.util.Locale;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class StartFrame extends javax.swing.JFrame {
    private Map<String, Integer> mapaKategorii;
    
    
    public StartFrame() {
        initComponents();
        setTitle("Fiszki - strona główna");
        setSize(550, 400);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        
        
        //pobranie kategorii z bazy
        mapaKategorii = BazaDanych.pobierzKategorie();
        cmbKategorie.removeAllItems(); //usunięcie domyślnych kategorii

        if (mapaKategorii != null && !mapaKategorii.isEmpty()) {
            for (String nazwa : mapaKategorii.keySet()) {
                cmbKategorie.addItem(nazwa);
            }
            cmbKategorie.setSelectedIndex(0);
            } else {
                JOptionPane.showMessageDialog(this, "Brak kategorii. Proszę dodać kategorię.", "Informacja", JOptionPane.WARNING_MESSAGE);
            }
    }

    private void otworzSlowaFrame() {
        String wybranaKategoria = (String) cmbKategorie.getSelectedItem();
        if (wybranaKategoria == null) {
            JOptionPane.showMessageDialog(this, "Nie wybrano kategorii.", "Błąd", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int kategoriaId = mapaKategorii.getOrDefault(wybranaKategoria, 1);
        new SlowaFrame(kategoriaId).setVisible(true);
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlStart = new javax.swing.JPanel();
        lblWybierzKat = new javax.swing.JLabel();
        cmbKategorie = new javax.swing.JComboBox<>();
        btnRozpocznij = new javax.swing.JButton();
        btnModyfikuj = new javax.swing.JButton();
        mbrMenuStart = new javax.swing.JMenuBar();
        mnuOProgramie = new javax.swing.JMenu();
        mniInstrukcja = new javax.swing.JMenuItem();
        mniOProgramie = new javax.swing.JMenuItem();
        mnuWyjscie = new javax.swing.JMenu();
        mniWyjdz = new javax.swing.JMenuItem();

        lblWybierzKat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblWybierzKat.setText("Wybierz kategorię");

        cmbKategorie.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbKategorie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbKategorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbKategorieActionPerformed(evt);
            }
        });

        btnRozpocznij.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRozpocznij.setText("Rozpocznij");
        btnRozpocznij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRozpocznijActionPerformed(evt);
            }
        });

        btnModyfikuj.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnModyfikuj.setText("Modyfikuj");
        btnModyfikuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModyfikujActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlStartLayout = new javax.swing.GroupLayout(pnlStart);
        pnlStart.setLayout(pnlStartLayout);
        pnlStartLayout.setHorizontalGroup(
            pnlStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStartLayout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addGroup(pnlStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStartLayout.createSequentialGroup()
                        .addComponent(lblWybierzKat, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStartLayout.createSequentialGroup()
                        .addGroup(pnlStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbKategorie, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlStartLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(pnlStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnModyfikuj, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRozpocznij, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(126, 126, 126))))
        );
        pnlStartLayout.setVerticalGroup(
            pnlStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStartLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblWybierzKat)
                .addGap(18, 18, 18)
                .addComponent(cmbKategorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRozpocznij)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModyfikuj)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        mnuOProgramie.setText("O programie");

        mniInstrukcja.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniInstrukcja.setText("Instrukcja");
        mniInstrukcja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniInstrukcjaActionPerformed(evt);
            }
        });
        mnuOProgramie.add(mniInstrukcja);

        mniOProgramie.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniOProgramie.setText("O programie");
        mniOProgramie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniOProgramieActionPerformed(evt);
            }
        });
        mnuOProgramie.add(mniOProgramie);

        mbrMenuStart.add(mnuOProgramie);

        mnuWyjscie.setText("Wyjście");
        mnuWyjscie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuWyjscieActionPerformed(evt);
            }
        });

        mniWyjdz.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniWyjdz.setText("Wyjdź");
        mniWyjdz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniWyjdzActionPerformed(evt);
            }
        });
        mnuWyjscie.add(mniWyjdz);

        mbrMenuStart.add(mnuWyjscie);

        setJMenuBar(mbrMenuStart);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(pnlStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(pnlStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbKategorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbKategorieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbKategorieActionPerformed

    private void btnRozpocznijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRozpocznijActionPerformed
        String wybranaKategoria = (String) cmbKategorie.getSelectedItem();
        int kategoriaId = mapaKategorii.containsKey(wybranaKategoria) ? mapaKategorii.get(wybranaKategoria) : 1;
        new SlowaFrame(kategoriaId).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRozpocznijActionPerformed

    private void mnuWyjscieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuWyjscieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuWyjscieActionPerformed

    private void mniWyjdzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniWyjdzActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mniWyjdzActionPerformed

    private void mniOProgramieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniOProgramieActionPerformed
        JOptionPane.showMessageDialog(StartFrame.this, 
            "Fiszki Polsko - Hiszpańskie.\nProgram Fiszki został stworzony, aby ułatwić naukę języka hiszpańskiego.\nAutor: Agnieszka Gazińska",
            "O programie", 
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_mniOProgramieActionPerformed

    private void mniInstrukcjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniInstrukcjaActionPerformed
        JOptionPane.showMessageDialog(StartFrame.this, 
            "Rozpoczęcie nauki:\n\nAby rozpocząć naukę, wybierz kategorię słów z menu rozwijanego, a następnie kliknij przycisk 'Ropocznij'.\n\nModyfikacja:\n\nW celu modyfikacji kategorii i słówek kliknij przycisk 'Modyfikuj' i podążaj za instrukcjami na stronie, która się wyświetli.\n\nStatystyki:\n\nAby śledzić swoje postępy, kliknij przycisk 'Statystyki'.",
            "Instrukcja",
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_mniInstrukcjaActionPerformed

    private void btnModyfikujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModyfikujActionPerformed
       new ModyfikujFrame().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnModyfikujActionPerformed

    /**
     * @param args the command line arguments
     */
      public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        System.setProperty("file.encoding", "UTF-8");
        
        // Ustawienie domyślnego kodowania i lokalizacji
        Locale.setDefault(Locale.forLanguageTag("pl-PL"));
        java.awt.EventQueue.invokeLater(() -> {
            new StartFrame().setVisible(true);
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModyfikuj;
    private javax.swing.JButton btnRozpocznij;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbKategorie;
    private javax.swing.JLabel lblWybierzKat;
    private javax.swing.JMenuBar mbrMenuStart;
    private javax.swing.JMenuItem mniInstrukcja;
    private javax.swing.JMenuItem mniOProgramie;
    private javax.swing.JMenuItem mniWyjdz;
    private javax.swing.JMenu mnuOProgramie;
    private javax.swing.JMenu mnuWyjscie;
    private javax.swing.JPanel pnlStart;
    // End of variables declaration//GEN-END:variables
    private SlowaFrame sf;
    private BazaDanych bd;
}
