
package frontend;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;

public class StatystykiFrame extends javax.swing.JFrame {

    public StatystykiFrame(int poprawne, int wszystkie, double procent, double czas) {
        initComponents();
        
        txtWynik.setText(poprawne + "/" + wszystkie);
        txtCzas.setText(formatCzas(czas));
        
        setTitle("Koniec nauki");
        setSize(400, 300);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        txtWynik.setEditable(false);
        txtCzas.setEditable(false);

        revalidate();
        repaint();
        setVisible(true);
    }
    
    private String formatCzas(double czasSekundy) {
        int hours = (int) (czasSekundy / 3600);
        int minutes = (int) ((czasSekundy % 3600) / 60);
        int seconds = (int) (czasSekundy % 60);

        return String.format("%02d:%02d:%02d", hours, minutes, seconds);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlKoniecNauki = new javax.swing.JPanel();
        lblKoniec = new javax.swing.JLabel();
        lblWynik = new javax.swing.JLabel();
        lblCzas = new javax.swing.JLabel();
        txtWynik = new javax.swing.JTextArea();
        txtCzas = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuStronaGlowna = new javax.swing.JMenu();
        mniStronaGlowna = new javax.swing.JMenuItem();
        mnuZamknij = new javax.swing.JMenu();
        mniZamknij = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblKoniec.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblKoniec.setText("Koniec nauki!");

        lblWynik.setText("Wynik:");

        lblCzas.setText("Czas:");

        txtWynik.setColumns(20);
        txtWynik.setRows(5);

        txtCzas.setColumns(20);
        txtCzas.setRows(5);

        javax.swing.GroupLayout pnlKoniecNaukiLayout = new javax.swing.GroupLayout(pnlKoniecNauki);
        pnlKoniecNauki.setLayout(pnlKoniecNaukiLayout);
        pnlKoniecNaukiLayout.setHorizontalGroup(
            pnlKoniecNaukiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKoniecNaukiLayout.createSequentialGroup()
                .addGroup(pnlKoniecNaukiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlKoniecNaukiLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(lblKoniec))
                    .addGroup(pnlKoniecNaukiLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(pnlKoniecNaukiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlKoniecNaukiLayout.createSequentialGroup()
                                .addComponent(lblCzas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCzas, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                            .addGroup(pnlKoniecNaukiLayout.createSequentialGroup()
                                .addComponent(lblWynik, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtWynik, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        pnlKoniecNaukiLayout.setVerticalGroup(
            pnlKoniecNaukiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKoniecNaukiLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblKoniec)
                .addGroup(pnlKoniecNaukiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlKoniecNaukiLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblWynik))
                    .addGroup(pnlKoniecNaukiLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(txtWynik, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlKoniecNaukiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCzas)
                    .addComponent(txtCzas, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        mnuStronaGlowna.setText("Strona główna");

        mniStronaGlowna.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniStronaGlowna.setText("Wróć do strony głównej");
        mniStronaGlowna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniStronaGlownaActionPerformed(evt);
            }
        });
        mnuStronaGlowna.add(mniStronaGlowna);

        jMenuBar1.add(mnuStronaGlowna);

        mnuZamknij.setText("Zamknij okno");

        mniZamknij.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniZamknij.setText("Zamknij okno");
        mniZamknij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniZamknijActionPerformed(evt);
            }
        });
        mnuZamknij.add(mniZamknij);

        jMenuBar1.add(mnuZamknij);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlKoniecNauki, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlKoniecNauki, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniStronaGlownaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniStronaGlownaActionPerformed
        new StartFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mniStronaGlownaActionPerformed

    private void mniZamknijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniZamknijActionPerformed
        this.dispose();
    }//GEN-LAST:event_mniZamknijActionPerformed

    public static void main(String[] args) {
        // Przykład testowy
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                new StatystykiFrame(8, 10, 80.0, 15.5).setVisible(true); // Testowe dane
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblCzas;
    private javax.swing.JLabel lblKoniec;
    private javax.swing.JLabel lblWynik;
    private javax.swing.JMenuItem mniStronaGlowna;
    private javax.swing.JMenuItem mniZamknij;
    private javax.swing.JMenu mnuStronaGlowna;
    private javax.swing.JMenu mnuZamknij;
    private javax.swing.JPanel pnlKoniecNauki;
    private javax.swing.JTextArea txtCzas;
    private javax.swing.JTextArea txtWynik;
    // End of variables declaration//GEN-END:variables

}